# Generated by Django 4.2.1 on 2023-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='test',
            field=models.TextField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
